module.exports.doctors=[
    {
        name:'Dr. Raj Srivastav',
        dept:'Cardiology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1200',
    },
    {
        name:'Dr. K. Ramak',
        dept:'Cardiology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1201',
    },
    {
        name:'Dr. V. Selvam',
        dept:'Cardiology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1202',
    },
    {
        name:'Dr. Presith Tripathi',
        dept:'Cardiology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1203',
    },
    {
        name:'Dr. Sneha Patel',
        dept:'Cardiology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1204',
    },
    {
        name:'Dr. Ramesh Choudhary',
        dept:'Gynecology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1205',
    },
    {
        name:'Dr. Priya Singh',
        dept:'Gynecology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'1PM-5PM',
        regno:'1206',
    },
    {
        name:'Dr. Rajesh Verma',
        dept:'Gynecology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'12PM-5PM',
        regno:'1207',
    },
    {
        name:'Dr. Meena Desai',
        dept:'Gynecology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1208',
    },
    {
        name:'Dr. Ashish Saxena',
        dept:'Gynecology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1209',
    },
    {
        name:'Dr. Shalini Khanna',
        dept:'Hepatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1210',
    },
    {
        name:'Dr. Kavita Agarwal',
        dept:'Hepatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'1PM-5PM',
        regno:'1211',
    },
    {
        name:'Dr. Sachin Kapoor',
        dept:'Hepatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'12PM-5PM',
        regno:'1211',
    },
    {
        name:'Dr. Amit Patel',
        dept:'Hepatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1212',
    },
    {
        name:'Dr. Swati Sharma',
        dept:'Hepatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1213',
    },
    {
        name:'Dr. Arvind Kumar',
        dept:'Neurology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1214',
    },
    {
        name:'Dr. Siddharth Kapoor',
        dept:'Neurology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'1PM-5PM',
        regno:'1215',
    },
    {
        name:'Dr. Abhishek Sharma',
        dept:'Neurology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'12PM-5PM',
        regno:'1216',
    },
    {
        name:'Dr. Priyanka Khanna',
        dept:'Neurology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1217',
    },
    {
        name:'Dr. Sangeeta Choudhary',
        dept:'Neurology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1218',
    },
    {
        name:'Dr. Rajeev Kumar',
        dept:'Opthalmology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1219',
    },
    {
        name:'Dr. Deepika Verma',
        dept:'Opthalmology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'1PM-5PM',
        regno:'1220',
    },
    {
        name:'Dr. Rohit Joshi',
        dept:'Opthalmology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'12PM-5PM',
        regno:'1221',
    },
    {
        name:'Dr. Neha Bansal',
        dept:'Opthalmology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1222',
    },
    {
        name:'Dr. Aisha Khan',
        dept:'Opthalmology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1223',
    },
    {
        name:'Dr. Arjun Mehta',
        dept:'Pediatrics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1224',
    },
    {
        name:'Dr. Kavya Gupta',
        dept:'Pediatrics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'1PM-5PM',
        regno:'1225',
    },
    {
        name:'Dr. Rajan Patel',
        dept:'Pediatrics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'12PM-5PM',
        regno:'1226',
    },
    {
        name:'Dr. Shreya Verma',
        dept:'Pediatrics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1227',
    },
    {
        name:'Dr. Aarav Sharma',
        dept:'Pediatrics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1228',
    },
    {
        name:'Dr. Naina Patel',
        dept:'Pediatrics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9PM-1AM',
        regno:'1229',
    },
    {
        name:'Dr. Rohan Singh',
        dept:'Dermatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-^PM',
        regno:'1230',
    },
    {
        name:'Dr. Aman Sharma',
        dept:'Dermatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1231',
    },
    {
        name:'Dr. Priya Kapoor',
        dept:'Dermatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9AM-5PM',
        regno:'1232',
    },
    {
        name:'Dr. Rajesh Kumar',
        dept:'Dermatology',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'11AM-5PM',
        regno:'1233',
    },
    {
        name:'Dr. Aishwarya Patel',
        dept:'Dentistry',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1234',
    },
    {
        name:'Dr. Anil Kapoor',
        dept:'Dentistry',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-5PM',
        regno:'1235',
    },
    {
        name:'Dr. Siddharth Rajan',
        dept:'Dentistry',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'1PM-5PM',
        regno:'1236',
    },
    {
        name:'Dr. Neeta Reddy',
        dept:'Dentistry',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'12PM-5PM',
        regno:'1237',
    },
    {
        name:'Dr. Ramesh Choudhary',
        dept:'Dentistry',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'10AM-11AM',
        regno:'1238',
    },
    {
        name:'Dr. Vikram Mehta',
        dept:'Orthopaedics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9AM-11AM',
        regno:'1239',
    },
    {
        name:'Dr. Nisha Sharma',
        dept:'Orthopaedics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9AM-11AM',
        regno:'1240',
    },
    {
        name:'Dr. Rahul Kapoor',
        dept:'Orthopaedics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9AM-11AM',
        regno:'1241',
    },
    {
        name:'Dr. Sneha Reddy',
        dept:'Orthopaedics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9AM-11AM',
        regno:'1242',
    },
    {
        name:'Dr. Rajesh Kumar',
        dept:'Orthopaedics',
        description: 'MBBS',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/813px-Unknown_person.jpg?20200423155822",
        days:'MON-FRI',
        timings:'9AM-11AM',
        regno:'1243',
    }
    

];
